// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Schema.Model.Templates
{
    using Schema.Model;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Model\Templates\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class EntityTemplate : CodeGeneration.Logic.GenericTemplating.CodeTemplate<Schema.Model.Entity>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\n\r\nnamespace Sample.Presentation.Domain\r\n{\r\n\tpublic class ");
            
            #line 7 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Model\Templates\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Metadata.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 9 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Model\Templates\EntityTemplate.tt"

	foreach (var field in Metadata.Fields)
	{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 13 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Model\Templates\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 13 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Model\Templates\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 14 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Model\Templates\EntityTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
