// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Schema.Templates.Database
{
    using CodeGeneration.Logic.Migrations;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class MigrationTemplate : MigrationTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("USE \"");
            
            #line 5 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeySpace));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n");
            
            #line 7 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 foreach (var viewDelta in Metadata.ModifiedItems) { 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 8 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 foreach (var field in viewDelta.Value.ComplexCollectionDeltas["Fields"].RemovedItems) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 9 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 if (field.IsSearchable) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tDROP INDEX \"");
            
            #line 10 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDelta.Key));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 10 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("_idx\";\r\n\t\t");
            
            #line 11 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tALTER TABLE \"");
            
            #line 13 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDelta.Key));
            
            #line default
            #line hidden
            this.Write("\" DROP \"");
            
            #line 13 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t");
            
            #line 14 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 16 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 foreach (var field in viewDelta.Value.ComplexCollectionDeltas["Fields"].AddedItems) { 
            
            #line default
            #line hidden
            this.Write("\t\tALTER TABLE \"");
            
            #line 17 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDelta.Key));
            
            #line default
            #line hidden
            this.Write("\" ADD \"");
            
            #line 17 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\" ");
            
            #line 17 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Type));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t\t");
            
            #line 19 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 if (field.IsSearchable) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tCREATE INDEX \"");
            
            #line 20 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDelta.Key));
            
            #line default
            #line hidden
            this.Write("\".\"");
            
            #line 20 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t");
            
            #line 21 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 22 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 24 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 foreach (var delta in viewDelta.Value.ComplexCollectionDeltas["Fields"].ModifiedItems) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 25 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 if (delta.Value.SimplePropertyDeltas.ContainsKey("IsSearchable")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 26 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 if (delta.Value.SimplePropertyDeltas["IsSearchable"].NewValue) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tCREATE INDEX \"");
            
            #line 27 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDelta.Key));
            
            #line default
            #line hidden
            this.Write("\".\"");
            
            #line 27 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delta.Key));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t");
            
            #line 28 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tDROP INDEX \"");
            
            #line 29 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewDelta.Key));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 29 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delta.Key));
            
            #line default
            #line hidden
            this.Write("_idx\";\r\n\t\t\t");
            
            #line 30 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 31 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 32 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 33 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\dev\MasterThesis\impl\SampleProject\Domain\Schema\Schema.Templates\Database\MigrationTemplate.tt"

private global::CodeGeneration.Logic.Migrations.ComplexCollectionDelta _MetadataField;

/// <summary>
/// Access the Metadata parameter of the template.
/// </summary>
private global::CodeGeneration.Logic.Migrations.ComplexCollectionDelta Metadata
{
    get
    {
        return this._MetadataField;
    }
}

private string _KeySpaceField;

/// <summary>
/// Access the KeySpace parameter of the template.
/// </summary>
private string KeySpace
{
    get
    {
        return this._KeySpaceField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool MetadataValueAcquired = false;
if (this.Session.ContainsKey("Metadata"))
{
    if ((typeof(global::CodeGeneration.Logic.Migrations.ComplexCollectionDelta).IsAssignableFrom(this.Session["Metadata"].GetType()) == false))
    {
        this.Error("The type \'CodeGeneration.Logic.Migrations.ComplexCollectionDelta\' of the paramete" +
                "r \'Metadata\' did not match the type of the data passed to the template.");
    }
    else
    {
        this._MetadataField = ((global::CodeGeneration.Logic.Migrations.ComplexCollectionDelta)(this.Session["Metadata"]));
        MetadataValueAcquired = true;
    }
}
if ((MetadataValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Metadata");
    if ((data != null))
    {
        if ((typeof(global::CodeGeneration.Logic.Migrations.ComplexCollectionDelta).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'CodeGeneration.Logic.Migrations.ComplexCollectionDelta\' of the paramete" +
                    "r \'Metadata\' did not match the type of the data passed to the template.");
        }
        else
        {
            this._MetadataField = ((global::CodeGeneration.Logic.Migrations.ComplexCollectionDelta)(data));
        }
    }
}
bool KeySpaceValueAcquired = false;
if (this.Session.ContainsKey("KeySpace"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["KeySpace"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'KeySpace\' did not match the type of th" +
                "e data passed to the template.");
    }
    else
    {
        this._KeySpaceField = ((string)(this.Session["KeySpace"]));
        KeySpaceValueAcquired = true;
    }
}
if ((KeySpaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("KeySpace");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'KeySpace\' did not match the type of th" +
                    "e data passed to the template.");
        }
        else
        {
            this._KeySpaceField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class MigrationTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
